image: registry.gitlab.com/junte/docker-hub/docker:19

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:${CI_PIPELINE_ID}
  DOCKER_CACHE_IMAGE: $CI_REGISTRY_IMAGE/tmp:latest

stages:
  - pre_build
  - build

lint_dockerfile:
  image: hadolint/hadolint:v1.18.0-6-ga0d655d-debian
  stage: pre_build
  script:
    - hadolint Dockerfile

build:
  stage: build
  services:
    - registry.gitlab.com/junte/docker-hub/docker:19-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $DOCKER_CACHE_IMAGE || true
    - docker build --cache-from $DOCKER_CACHE_IMAGE -t $DOCKER_CACHE_IMAGE --target builder .
    - docker build --cache-from $DOCKER_CACHE_IMAGE -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
    - docker push $DOCKER_CACHE_IMAGE
